#! /usr/bin/env bash

newline=$'\n'

exampleNames=()
examples=()
readingExample=false
waitingForOutputBlock=false
readingOutputBlock=false

mostRecentH1=''
mostRecentH2=''
mostRecentH5=''

lineNumber=0

while IFS="" read -r line || [ -n "$line" ]
do
  (( lineNumber++ ))
  if [[ "$line" =~ ^\#[[:space:]](.*)$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
  then
    mostRecentH1="${BASH_REMATCH[1]}"
    echo "$mostRecentH1"
    mostRecentH2=''
    mostRecentH5=''
  elif [[ "$line" =~ ^\#\#[[:space:]]\[\`([^\]]+)\`\].*$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
  then
    mostRecentH2="${BASH_REMATCH[1]}"
    echo "  $mostRecentH2"
    mostRecentH5=''
  elif [[ "$line" =~ ^\#\#[[:space:]](.*)$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
  then
    mostRecentH2="${BASH_REMATCH[1]}"
    echo "  $mostRecentH2"
    mostRecentH5=''
  elif [[ "$line" =~ ^\#\#\#\#\#[[:space:]]\[\`([^\]]+)\`\].*$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
  then
    mostRecentH5="${BASH_REMATCH[1]}"
    echo "    $mostRecentH5"
  elif [[ "$line" =~ ^\#\#\#\#\#[[:space:]](.*)$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
  then
    mostRecentH5="${BASH_REMATCH[1]}"
    echo "    $mostRecentH5"
  elif [ "$line" = "<!-- OUTPUT -->" ]
  then
    # Add a `- code` to the previous example block
    # and now continue reading into it
    examples[$(( ${#examples[@]} - 1 ))]+="- code${newline}# => '"
    waitingForOutputBlock=true
  elif [[ "$line" =~ ^\`\`\`sh ]] && [ "$waitingForOutputBlock" = true ]
  then
    readingExample=true
    readingOutputBlock=true
    waitingForOutputBlock=false
  elif [[ "$line" =~ ^\`\`\`sh ]]
  then
    exampleName="$mostRecentH1 $mostRecentH2 $mostRecentH5"
    exampleName="${exampleName//[^a-zA-Z0-9]/_}"
    exampleName="${exampleName//__/_}"
    exampleName="${exampleName%_}"
    exampleNames+=("$exampleName")
    [ -z "${exampleName// /}" ] && { echo "Missing name for example at line number $lineNumber" >&2; exit 1; }
    examples+=("") 
    readingExample=true
  elif [[ "$line" =~ ^\`\`\` ]]
  then
    [ "$readingOutputBlock" = true ] && examples[$(( ${#examples[@]} - 1 ))]+="'"
    readingExample=false
    readingOutputBlock=false
  elif [ "$readingExample" = true ] && [ "$readingOutputBlock" = true ]
  then
    examples[$(( ${#examples[@]} - 1 ))]+="$line\n"
  elif [ "$readingExample" = true ]
  then
    examples[$(( ${#examples[@]} - 1 ))]+="$line${newline}"
  fi
done < docs/_pages/index.md

echo "Found ${#examples[@]} examples."

dir=examples/documentation/userGuide

[ -d "$dir" ] && rm -r "$dir"
mkdir -p "$dir"

exampleIndex=0
specNumber=1

while [ $exampleIndex -lt "${#examples[@]}" ]
do
  source="${examples[$exampleIndex]}"
  exampleName="${exampleNames[$exampleIndex]}"
  specFile="$dir/${exampleName// /_}.spec.sh"

  exampleNumber=1
  commands=()

  while IFS="" read -r line || [ -n "$line" ]
  do
    if [[ "$line" =~ ^\#[[:space:]]\=\>[[:space:]][\'\"](.*)[\'\"]$ ]]
    then
      expectedOutput="${BASH_REMATCH[1]}"

      # Ah ha! It's good for speccing!
      if [ ! -f "$specFile" ]
      then
        echo -e "source shellpen.sh${newline}" >> "$specFile"
        echo -e "shellpen -${newline}" >> "$specFile"
        echo "Writing $specFile"
        (( specNumber++ ))
      fi

      # First the function wrapping all of the called commands
      echo "commandGroup$exampleNumber() {" >> "$specFile"
      command=''
      for command in "${commands[@]}"
      do
        echo -e "  $command" >> "$specFile"
      done
      echo -e "}${newline}" >> "$specFile"

      # Now a spec which executes the commandgroup and verifies its output
      echo "@spec.commandGroup$exampleNumber() {" >> "$specFile"
      echo "  read -r -d '' expected <<'EXPECTED'" >> "$specFile"
      echo -e "$expectedOutput" >> "$specFile"
      echo "EXPECTED" >> "$specFile"
      echo "  expect { commandGroup$exampleNumber } toContain \"\$expected\"" >> "$specFile"
      echo -e "}${newline}" >> "$specFile"

      (( exampleNumber++ ))
    else
      # Skip lines which recreate 'shellpen -'
      if [[ "$line" = *"shellpen -"* ]]
      then
        commands+=("# $line # Skipped recreating - pen")
      else
        commands+=("$line")
      fi
    fi
  done <<< "$source"

  (( exampleIndex++ ))
done