# Private Variables
_SHELLPEN_SOURCES=("default")
_SHELLPEN_SOURCECODE=("")
_SHELLPEN_OPTION_OPEN=("")
_SHELLPEN_INDENT_LEVELS=(0)
_SHELLPEN_CURRENT_SOURCE_INDEX=0

# Public Variables
[ -z "$SHELLPEN_INDENT" ] && SHELLPEN_INDENT="  "