# Private Variables
_SHELLPEN_CURRENT_SOURCE_INDEX=0
_SHELLPEN_SOURCES=("default")
_SHELLPEN_SOURCECODE=("")
_SHELLPEN_INDENT_LEVELS=(0)
_SHELLPEN_OPTION_OPEN=("")
_SHELLPEN_FUNCTION_OPEN=("")
_SHELLPEN_CASE_OPEN=("")
_SHELLPEN_MAIN_FUNCTION=("")
_SHELLPEN_SHEBANG=("#! /usr/bin/env bash")

# Public Variables
[ -z "$SHELLPEN_INDENT" ] && SHELLPEN_INDENT="  "