name: BASH 5.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: 'bash --version | head -1'
        shell: bash
      - run: bin/spec
        shell: bash
        env:
          VERBOSE: true
          SHELLPEN_RANDOM_SOURCE: /dev/random