name: BASH 4.3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-16.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: 'bash --version | head -1'
        shell: bash
      - run: bin/spec
        shell: bash
        env:
          VERBOSE: true
          SHELLPEN_URANDOM: false