name: BASH 5.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: 'bash --version | head -1'
        shell: bash
      - run: echo Will read from random
        shell: bash
      - run: cat /dev/random | base64 | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
        shell: bash
      - run: echo Next read from urandom
        shell: bash
      - run: cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
        shell: bash